name: Release Origami Component
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - name: Repository name
      id: repo_name
      run: echo ::set-output name=REPO_NAME::$(echo $GITHUB_REPOSITORY | cut -d / -f 2)
    - name: Get the version
      id: version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - run: npx occ ${{ steps.version.outputs.VERSION }} --name ${{ steps.repo_name.outputs.REPO_NAME }} --repository ${{ steps.repo_name.outputs.REPO_NAME }}
    - run: npx occ ${{ steps.version.outputs.VERSION }}
    - run: npx snyk monitor --org=financial-times --project-name=Financial-Times/o-ads
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
