name: Unit test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm config set prefix "$HOME/.local"
    - run: npm i -g origami-build-tools@^8
    - run: npx obt install
    - run: npx obt build --production
    - run: npx obt verify
    - run: npm run checksizes
    # `obt test` doesn't work because of custom karma config, so we run:
    - run: npm run test-unit
